before_script:
    - module load gfortran/6.2
    - module load openmpi/3.1.3
    - module load fftw/3.3.8

stages:
    - build
    - test
    - deploy

serial_build:
    stage: build
    script:
        - mkdir ser_build
        - cd ser_build
        - FC=gfortran cmake -DFFTW_DIR=$FFTW ..
        - make
    artifacts:
        paths:
        - ./ser_build
        expire_in: 1 week

parallel_build:
    stage: build
    script:
        - mkdir par_build
        - cd par_build
        - FC=mpifort cmake -DPARALLEL=ON -DFFTW_DIR=$FFTW ..
        - make
    artifacts:
        paths:
        - ./par_build
        expire_in: 1 week

ser_test_gauss3d:
    stage: test
    script:
        - ./ser_build/tests/gauss3d

par_test_gauss3d:
    stage: test
    script:
        - mpirun -n 2 ./par_build/tests/gauss3d

ser_test_sedov3d:
    stage: test
    script:
        - ./ser_build/tests/sedov3d

par_test_sedov3d:
    stage: test
    script:
        - mpirun -n 2 ./par_build/tests/sedov3d

ser_test_bondi3d:
    stage: test
    script:
        - ./ser_build/tests/bondi3d

par_test_bondi3d:
    stage: test
    script:
        - mpirun -n 2 ./par_build/tests/bondi3d

ser_test_sedov2d:
    stage: test
    script:
        - ./ser_build/tests/sedov2d

par_test_sedov2d:
    stage: test
    script:
        - mpirun -n 2 ./par_build/tests/sedov2d

ser_test_bondi2d:
    stage: test
    script:
        - ./ser_build/tests/bondi2d

ser_test_riemann3d:
    stage: test
    script:
        - ./ser_build/tests/riemann3d

par_test_bondi2d:
    stage: test
    script:
        - mpirun -n 2 ./par_build/tests/bondi2d

ser_test_planet2d:
    stage: test
    script:
        - ./ser_build/tests/planet2d

ser_test_poiseuille:
    stage: test
    script:
        - ./ser_build/tests/poiseuille

par_test_poiseuille:
    stage: test
    script:
        - mpirun -n 2 ./par_build/tests/poiseuille

ser_test_pringle:
    stage: test
    script:
        - ./ser_build/tests/pringle

par_test_pringle:
    stage: test
    script:
        - mpirun -n 2 ./par_build/tests/pringle

ser_test_KHI2D:
    stage: test
    script:
       - ./ser_build/tests/KHI2D

ser_test_KHI2D_sphere:
    stage: test
    script:
       - ./ser_build/tests/KHI2D_sphere

ser_test_KHI3D:
    stage: test
    script:
       - ./ser_build/tests/KHI3D

set_test_shear:
    stage: test
    script:
       - ./ser_build/tests/shear

ser_test_rootstest:
    stage: test
    script:
       - ./ser_build/tests/rootstest

deploy_github:
    stage: deploy
    script:
        - git checkout master
        - git merge origin/master
        - git remote | grep -q origin_github && git remote remove origin_github
        - git remote add origin_github git@github.com:tillense/fosite.git
        - git push origin_github master --tags
    environment:
      name: deploy_github
    when: manual
    only:
        - tags

deploy_website:
    stage: deploy
    script:
        - git checkout master
        - git merge origin/master
        - git remote | grep -q origin_website && git remote remove origin_website
        - git remote add origin_website webadmin@portia:/home/webadmin/src/fosite/git
        - git push origin_website master -f --tags
    environment:
      name: deploy_website
    when: manual
    only:
        - tags
